sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t raghvendra/react-test -f ./client/Dockerfile.dev ./client

script:
  - dcoker run -e CI=true raghvendra/react-test npm test 

after_success:
  - docker build -t raghvendra/multi-client  ./client
  - docker build -t raghvendra/multi-nginx  ./nginx
  - docker build -t raghvendra/multi-server  ./server
  - docker build -t raghvendra/multi-worker  ./worker

#Login to docker
- echo "$DOCKER_PASSWORD | docker login -u "$DOCKERID" --password-stdin

#Docker pus
- dcoker push raghvendra/multi-client
- dcoker push raghvendra/multi-nginx
- dcoker push raghvendra/multi-server
- dcoker push raghvendra/multi-worker
